import { api, unwrap } from './api';
import type { ApiResponse, Paginated } from '../types';
const get = <T>(url: string, params?: object) => api.get<ApiResponse<T>>(url, { params }).then(unwrap);
const post = <T>(url: string, body?: unknown) => api.post<ApiResponse<T>>(url, body).then(unwrap);
const patch = <T>(url: string, body?: unknown) => api.patch<ApiResponse<T>>(url, body).then(unwrap);
const put = <T>(url: string, body?: unknown) => api.put<ApiResponse<T>>(url, body).then(unwrap);
const del = <T>(url: string) => api.delete<ApiResponse<T>>(url).then(unwrap);

export const schoolApi = {
  auth: { login: (body: object) => post<{ token: string; user: any; must_change_password: boolean }>('/auth/login', body), me: () => get<any>('/auth/me'), changePassword: (body: object) => post('/auth/change-password', body) },
  dashboard: () => get<any>('/dashboard'),
  setup: { status: () => get<any>('/setup/status'), initializeDemo: () => post<any>('/setup/demo') },
  backups: {
    list: () => get<any[]>('/backups'),
    create: () => post<any>('/backups'),
    download: (fileName: string) => api.get(`/backups/${encodeURIComponent(fileName)}`, { responseType: 'blob' }),
    restore: async (file: File) => { const form = new FormData(); form.append('database', file); return api.post<ApiResponse<any>>('/backups/restore', form, { headers: { 'Content-Type': 'multipart/form-data' } }).then(unwrap); }
  },
  upload: async (file: File) => { const form = new FormData(); form.append('file', file); return api.post<ApiResponse<any>>('/uploads', form, { headers: { 'Content-Type': 'multipart/form-data' } }).then(unwrap); },
  users: { list: (p?: object) => get<Paginated<any>>('/users', p), roles: () => get<any[]>('/users/roles'), permissions: () => get<any[]>('/users/permissions'), create: (body: object) => post('/users', body), update: (id: number, body: object) => patch(`/users/${id}`, body), reset: (id: number, body: object) => patch(`/users/${id}/reset-password`, body), remove: (id: number) => del(`/users/${id}`) },
  students: { list: (p?: object) => get<Paginated<any>>('/students', p), stats: () => get<any>('/students/stats'), nextIdentifiers: (p?: object) => get<{ admission_no: string; roll_no: string | null }>('/students/next-identifiers', p), get: (id: number) => get<any>(`/students/${id}`), classTestHistory: (id: number) => get<any[]>(`/students/${id}/class-tests`), academicResults: (id: number) => get<any[]>(`/students/${id}/results`), create: (body: object) => post('/students', body), update: (id: number, body: object) => patch(`/students/${id}`, body), remove: (id: number) => del(`/students/${id}`), restore: (id: number) => post(`/students/${id}/restore`), document: (id: number, body: object) => post(`/students/${id}/documents`, body), uploadDocuments: async (id: number, files: File[], onProgress?: (percent: number) => void) => { const form = new FormData(); files.forEach((file) => form.append('documents', file)); return api.post<ApiResponse<any[]>>(`/students/${id}/documents/upload`, form, { headers: { 'Content-Type': 'multipart/form-data' }, onUploadProgress: (event) => { if (event.total) onProgress?.(Math.round(event.loaded * 100 / event.total)); } }).then(unwrap); }, replaceDocument: async (studentId: number, documentId: number, file: File) => { const form = new FormData(); form.append('document', file); return api.post<ApiResponse<any>>(`/students/${studentId}/documents/${documentId}/replace`, form, { headers: { 'Content-Type': 'multipart/form-data' } }).then(unwrap); }, removeDocument: (studentId: number, documentId: number) => del(`/students/${studentId}/documents/${documentId}`), promote: (id: number, body: object) => post(`/students/${id}/promote`, body), autoPromote: (body: object) => post('/students/promotions/auto', body) },
  staff: { list: (p?: object) => get<Paginated<any>>('/staff', p), options: () => get<any[]>('/staff/options'), workspace: () => get<any>('/staff/me/workspace'), get: (id: number) => get<any>(`/staff/${id}`), create: (body: object) => post('/staff', body), update: (id: number, body: object) => patch(`/staff/${id}`, body), remove: (id: number) => del(`/staff/${id}`), salary: (id: number, body: object) => post(`/staff/${id}/salary-history`, body), departments: () => get<any[]>('/staff/departments'), addDepartment: (body: object) => post('/staff/departments', body), designations: () => get<any[]>('/staff/designations'), addDesignation: (body: object) => post('/staff/designations', body) },
  academic: { classes: (p?: object) => get<any[]>('/academic/classes', p), class: (id: number) => get<any>(`/academic/classes/${id}`), saveClass: (body: object, id?: number) => id ? patch(`/academic/classes/${id}`, body) : post('/academic/classes', body), deleteClass: (id: number) => del(`/academic/classes/${id}`), sections: (p?: object) => get<any[]>('/academic/sections', p), saveSection: (body: object, id?: number) => id ? patch(`/academic/sections/${id}`, body) : post('/academic/sections', body), deleteSection: (id: number) => del(`/academic/sections/${id}`), subjects: (p?: object) => get<any[]>('/academic/subjects', p), saveSubject: (body: object, id?: number) => id ? patch(`/academic/subjects/${id}`, body) : post('/academic/subjects', body), deleteSubject: (id: number) => del(`/academic/subjects/${id}`), classSubjects: (p?: object) => get<any[]>('/academic/class-subjects', p), saveClassSubject: (body: object, id?: number) => id ? patch(`/academic/class-subjects/${id}`, body) : post('/academic/class-subjects', body), deleteClassSubject: (id: number) => del(`/academic/class-subjects/${id}`), sessions: () => get<any[]>('/academic/sessions'), saveSession: (body: object, id?: number) => id ? patch(`/academic/sessions/${id}`, body) : post('/academic/sessions', body), examTypes: () => get<any[]>('/academic/exam-types'), saveExamType: (body: object, id?: number) => id ? patch(`/academic/exam-types/${id}`, body) : post('/academic/exam-types', body), deleteExamType: (id: number) => del(`/academic/exam-types/${id}`), rooms: () => get<any[]>('/academic/rooms'), saveRoom: (body: object, id?: number) => id ? patch(`/academic/rooms/${id}`, body) : post('/academic/rooms', body), deleteRoom: (id: number) => del(`/academic/rooms/${id}`) },
  timetable: { settings: () => get<any>('/timetable/settings'), saveSettings: (body: object) => patch('/timetable/settings', body), entries: (p: object) => get<any[]>('/timetable/entries', p), saveEntry: (body: object, id?: number) => id ? patch(`/timetable/entries/${id}`, body) : post('/timetable/entries', body), deleteEntry: (id: number) => del(`/timetable/entries/${id}`), savePeriod: (body: object, id?: number) => id ? patch(`/timetable/periods/${id}`, body) : post('/timetable/periods', body), deletePeriod: (id: number) => del(`/timetable/periods/${id}`) },
  attendance: { roster: (p: object) => get<any>('/attendance/roster', p), save: (body: object) => post('/attendance', body), lock: (id: number, locked: boolean) => patch(`/attendance/${id}/lock`, { locked }), daily: (p?: object) => get<any[]>('/attendance/reports/daily', p), monthly: (p: object) => get<any>('/attendance/reports/monthly', p), history: (studentId: number) => get<any>(`/attendance/students/${studentId}/history`), staff: (p?: object) => get<any[]>('/attendance/staff', p), saveStaff: (body: object) => post('/attendance/staff', body), markOwn: (body?: object) => post('/attendance/staff/me', body) },
  fees: { heads: () => get<any[]>('/fees/heads'), saveHead: (body: object, id?: number) => id ? patch(`/fees/heads/${id}`, body) : post('/fees/heads', body), deleteHead: (id: number) => del(`/fees/heads/${id}`), structures: (p?: object) => get<any[]>('/fees/structures', p), saveStructure: (body: object, id?: number) => id ? patch(`/fees/structures/${id}`, body) : post('/fees/structures', body), deleteStructure: (id: number) => del(`/fees/structures/${id}`), invoices: (p?: object) => get<Paginated<any>>('/fees/invoices', p), invoice: (id: number) => get<any>(`/fees/invoices/${id}`), createInvoice: (body: object) => post('/fees/invoices', body), generate: (body: object) => post('/fees/invoices/generate', body), void: (id: number) => post(`/fees/invoices/${id}/void`), payment: (body: object) => post('/fees/payments', body), receipt: (id: number) => get<any>(`/fees/payments/${id}/receipt`), reports: (p?: object) => get<any>('/fees/reports', p), reminderStatus: () => get<any>('/fees/reminders/status'), configureReminders: (body: object) => put('/fees/reminders/config', body), sendRemindersNow: () => post<any>('/fees/reminders/send-now'), income: (p?: object) => get<Paginated<any>>('/fees/income', p), saveIncome: (body: object, id?: number) => id ? patch(`/fees/income/${id}`, body) : post('/fees/income', body), deleteIncome: (id: number) => del(`/fees/income/${id}`), expenses: (p?: object) => get<Paginated<any>>('/fees/expenses', p), saveExpense: (body: object, id?: number) => id ? patch(`/fees/expenses/${id}`, body) : post('/fees/expenses', body), deleteExpense: (id: number) => del(`/fees/expenses/${id}`), categories: () => get<any[]>('/fees/expense-categories'), saveCategory: (body: object) => post('/fees/expense-categories', body), financeSummary: (p?: object) => get<any>('/fees/finance-summary', p) },
  assessments: { tests: (p?: object) => get<Paginated<any>>('/assessments/tests', p), test: (id: number) => get<any>(`/assessments/tests/${id}`), saveTest: (body: object, id?: number) => id ? patch(`/assessments/tests/${id}`, body) : post('/assessments/tests', body), testMarks: (id: number) => get<any[]>(`/assessments/tests/${id}/marks`), saveTestMarks: (id: number, marks: object[]) => put(`/assessments/tests/${id}/marks`, { marks }), publishTest: (id: number) => post(`/assessments/tests/${id}/publish`), exams: (p?: object) => get<any[]>('/assessments/exams', p), exam: (id: number) => get<any>(`/assessments/exams/${id}`), saveExam: (body: object, id?: number) => id ? patch(`/assessments/exams/${id}`, body) : post('/assessments/exams', body), saveExamSubject: (examId: number, body: object, subjectId?: number) => subjectId ? patch(`/assessments/exams/${examId}/subjects/${subjectId}`, body) : post(`/assessments/exams/${examId}/subjects`, body), examMarks: (examId: number, subjectId: number) => get<any[]>(`/assessments/exams/${examId}/subjects/${subjectId}/marks`), saveExamMarks: (examId: number, subjectId: number, marks: object[]) => put(`/assessments/exams/${examId}/subjects/${subjectId}/marks`, { marks }), transition: (id: number, action: string) => post(`/assessments/exams/${id}/${action}`), results: (id: number, p: object) => get<any[]>(`/assessments/exams/${id}/results`, p) },
  communication: { gateway: () => get<any>('/communication/gateway'), saveGateway: (body: object) => patch('/communication/gateway', body), templates: () => get<any[]>('/communication/templates'), saveTemplate: (body: object, id?: number) => id ? patch(`/communication/templates/${id}`, body) : post('/communication/templates', body), deleteTemplate: (id: number) => del(`/communication/templates/${id}`), logs: (p?: object) => get<Paginated<any>>('/communication/logs', p), send: (body: object) => post('/communication/send', body), resend: (id: number) => post(`/communication/logs/${id}/resend`), whatsapp: (body: object) => post<{url:string}>('/communication/whatsapp-link', body) },
  messaging: {
    providers: () => get<any[]>('/messaging/providers'),
    configurations: () => get<any[]>('/messaging/configurations'),
    configuration: (id: number) => get<any>(`/messaging/configurations/${id}`),
    saveConfiguration: (body: object, id?: number) => id ? patch(`/messaging/configurations/${id}`, body) : post('/messaging/configurations', body),
    deleteConfiguration: (id: number) => del(`/messaging/configurations/${id}`),
    validateConfiguration: (id: number) => post(`/messaging/configurations/${id}/validate`),
    testConfiguration: (id: number, body: object) => post(`/messaging/configurations/${id}/test`, body),
    templates: () => get<any[]>('/messaging/templates'),
    saveTemplate: (body: object, id?: number) => id ? patch(`/messaging/templates/${id}`, body) : post('/messaging/templates', body),
    deleteTemplate: (id: number) => del(`/messaging/templates/${id}`),
    send: (body: object) => post<any>('/messaging/send', body),
    logs: (p?: object) => get<Paginated<any>>('/messaging/logs', p),
    retry: (id: number) => post(`/messaging/logs/${id}/retry`),
    modemPorts: () => get<any[]>('/messaging/modem/ports'),
    modemConnect: (body: object) => post<any>('/messaging/modem/connect', body),
    modemDisconnect: (body: object) => post<any>('/messaging/modem/disconnect', body),
    modemInfo: (body: object) => post<any>('/messaging/modem/info', body)
  },
  settings: { branding: () => get<any>('/settings/branding'), all: () => get<any>('/settings'), save: (body: object) => put('/settings', body), roles: () => get<any[]>('/settings/roles'), role: (id: number) => get<any>(`/settings/roles/${id}`), saveRole: (body: object, id?: number) => id ? patch(`/settings/roles/${id}`, body) : post('/settings/roles', body), deleteRole: (id: number) => del(`/settings/roles/${id}`) },
  visitors: { list: (p?: object) => get<Paginated<any>>('/visitors', p), create: (body: object) => post('/visitors', body), checkout: (id: number, body?: object) => post(`/visitors/${id}/checkout`, body) },
  system: { reset: (body: object) => post<any>('/system/reset', body) },
  reports: { students: (p?: object) => get<any>('/reports/students', p), attendance: (p?: object) => get<any>('/reports/attendance', p), fees: (p?: object) => get<any>('/reports/fees', p), finance: (p?: object) => get<any>('/reports/finance', p), resultCard: (examId: number, studentId: number, p: object) => get<any>(`/reports/result-card/${examId}/${studentId}`, p), classTestCard: (testId: number, studentId: number) => get<any>(`/reports/class-test-card/${testId}/${studentId}`), awardList: (examId: number, p: object) => get<any>(`/reports/award-list/${examId}`, p), blankAward: (examId: number, p: object) => get<any>(`/reports/blank-award-list/${examId}`, p), timetable: (p: object) => get<any>('/reports/timetable', p), certificate: (studentId: number, p: object) => get<any>(`/reports/certificate/${studentId}`, p) }
};
