import { Router } from 'express';
import auth from './auth.routes';
import users from './user.routes';
import students from './student.routes';
import uploads from './upload.routes';
import staff from './staff.routes';
import academic from './academic.routes';
import timetable from './timetable.routes';
import attendance from './attendance.routes';
import fees from './fee.routes';
import assessments from './assessment.routes';
import communication from './communication.routes';
import messaging from './messaging.routes';
import settings from './settings.routes';
import dashboard from './dashboard.routes';
import reports from './report.routes';
import setup from './setup.routes';
import backups from './backup.routes';
import visitors from './visitor.routes';
import system from './system.routes';

export const apiRouter = Router();
apiRouter.get('/health', (_req, res) => res.json({ success: true, data: { status: 'ok' } }));
apiRouter.use('/auth', auth);
apiRouter.use('/users', users);
apiRouter.use('/students', students);
apiRouter.use('/uploads', uploads);
apiRouter.use('/staff', staff);
apiRouter.use('/academic', academic);
apiRouter.use('/timetable', timetable);
apiRouter.use('/attendance', attendance);
apiRouter.use('/fees', fees);
apiRouter.use('/assessments', assessments);
apiRouter.use('/communication', communication);
apiRouter.use('/messaging', messaging);
apiRouter.use('/settings', settings);
apiRouter.use('/dashboard', dashboard);
apiRouter.use('/reports', reports);
apiRouter.use('/setup', setup);
apiRouter.use('/backups', backups);
apiRouter.use('/visitors', visitors);
apiRouter.use('/system', system);
