import { Router } from 'express';
import * as controller from '../controllers/student.controller';
import { requireAuth, requirePermission } from '../middleware/auth';
import { studentDocumentUpload } from '../middleware/upload';
const router = Router();
router.use(requireAuth);
router.get('/stats', requirePermission('students.read'), controller.studentStats);
router.get('/next-identifiers', requirePermission('students.manage'), controller.nextIdentifiers);
router.get('/', requirePermission('students.read'), controller.listStudents);
router.post('/', requirePermission('students.manage'), controller.createStudent);
router.post('/promotions/auto', requirePermission('students.manage'), controller.autoPromote);
router.get('/:id/class-tests', requirePermission('students.read'), controller.classTestHistory);
router.get('/:id/results', requirePermission('students.read'), controller.academicResults);
router.get('/:id', requirePermission('students.read'), controller.getStudent);
router.patch('/:id', requirePermission('students.manage'), controller.updateStudent);
router.delete('/:id', requirePermission('students.manage'), controller.archiveStudent);
router.post('/:id/restore', requirePermission('students.manage'), controller.restoreStudent);
router.post('/:id/documents', requirePermission('students.manage'), controller.addDocument);
router.post('/:id/documents/upload', requirePermission('students.manage'), studentDocumentUpload.array('documents', 10), controller.uploadDocuments);
router.post('/:id/documents/:documentId/replace', requirePermission('students.manage'), studentDocumentUpload.single('document'), controller.replaceDocument);
router.delete('/:id/documents/:documentId', requirePermission('students.manage'), controller.removeDocument);
router.post('/:id/promote', requirePermission('students.manage'), controller.promote);
export default router;
