import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { Save, SlidersHorizontal } from 'lucide-react';
import { schoolApi } from '../../services/schoolApi';
import { queryKeys } from '../../services/queryKeys';
import { useMutationToast } from '../../hooks/useMutationToast';
import { PageHeader } from '../../components/common/PageHeader';
import { Tabs } from '../../components/common/Tabs';
import { Card } from '../../components/common/Card';
import { Button } from '../../components/common/Button';
import { Field, SelectInput, TextArea, TextInput } from '../../components/common/FormFields';
import { PhotoUploader } from '../../components/forms/PhotoUploader';
import { UsersPanel } from '../../components/forms/UsersPanel';
import { RolesPanel } from '../../components/forms/RolesPanel';
import { ExamTypesPanel } from '../../components/forms/ExamTypesPanel';
import { BackupRestorePanel } from '../../components/forms/BackupRestorePanel';
import { CertificateTemplatesPanel } from '../../components/forms/CertificateTemplatesPanel';
import { SchoolResetPanel } from '../../components/forms/SchoolResetPanel';
type Tab='school'|'users'|'roles'|'preferences'|'certificates'|'backups'|'reset';
export default function SettingsPage(){const [tab,setTab]=useState<Tab>('school');return <><PageHeader title="Settings" description="Control the school identity, security, roles, academic rules and localized operations."/><Tabs tabs={[{id:'school',label:'School profile'},{id:'users',label:'Users'},{id:'roles',label:'Roles & permissions'},{id:'preferences',label:'Rules & preferences'},{id:'certificates',label:'Certificate templates'},{id:'backups',label:'Backup & restore'},{id:'reset',label:'Reset school data'}]} value={tab} onChange={setTab}/><Card className="p-5">{tab==='school'&&<SchoolProfile/>}{tab==='users'&&<UsersPanel/>}{tab==='roles'&&<RolesPanel/>}{tab==='preferences'&&<Preferences/>}{tab==='certificates'&&<CertificateTemplatesPanel/>}{tab==='backups'&&<BackupRestorePanel/>}{tab==='reset'&&<SchoolResetPanel/>}</Card></>}
function SchoolProfile(){const {data}=useQuery({queryKey:queryKeys.settings.all,queryFn:schoolApi.settings.all});const save=useMutationToast((body:any)=>schoolApi.settings.save(body),{success:'School profile saved',sync:['settings']});const value=(key:string)=>data?.[key]?.value||'';const {register,handleSubmit,setValue,watch}=useForm<any>({values:{name:value('school.name'),name_ur:value('school.name_ur'),logo:value('school.logo'),address:value('school.address'),phone:value('school.phone'),email:value('school.email'),principal_name:value('school.principal_name'),timezone:value('school.timezone')||'Asia/Karachi',website:value('school.website'),tagline:value('school.tagline')}});return <form onSubmit={handleSubmit((values)=>save.mutate({settings:{'school.name':values.name,'school.name_ur':values.name_ur,'school.logo':values.logo,'school.address':values.address,'school.phone':values.phone,'school.email':values.email,'school.principal_name':values.principal_name,'school.timezone':values.timezone,'school.website':values.website,'school.tagline':values.tagline}}))} className="mx-auto max-w-3xl space-y-6"><div><h2 className="text-lg font-bold text-slate-800">School branding</h2><p className="mt-1 text-sm text-slate-500">This information appears on fee receipts, result cards, certificates and A4 reports.</p></div><Field label="School logo"><PhotoUploader value={watch('logo')} onChange={(path)=>setValue('logo',path)} name={watch('name')}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="School name"><TextInput {...register('name')}/></Field><Field label="School name (Urdu)"><TextInput className="urdu" {...register('name_ur')}/></Field><Field label="Phone"><TextInput {...register('phone')}/></Field><Field label="Email"><TextInput type="email" {...register('email')}/></Field><Field label="Principal name"><TextInput {...register('principal_name')}/></Field><Field label="Website"><TextInput type="url" placeholder="https://school.edu.pk" {...register('website')}/></Field><Field label="Tagline"><TextInput placeholder="Learning for a brighter future" {...register('tagline')}/></Field><Field label="Time zone"><SelectInput {...register('timezone')}><option value="Asia/Karachi">Asia/Karachi (Pakistan)</option><option value="UTC">UTC</option></SelectInput></Field></div><Field label="School address"><TextArea {...register('address')}/></Field><div className="flex justify-end"><Button type="submit" loading={save.isPending} icon={<Save className="h-4 w-4"/>}>Save school profile</Button></div></form>}
function Preferences(){const {data}=useQuery({queryKey:queryKeys.settings.all,queryFn:schoolApi.settings.all});const save=useMutationToast((body:any)=>schoolApi.settings.save(body),{success:'Preferences saved',sync:['settings']});const get=(key:string,def='')=>data?.[key]?.value||def;const {register,handleSubmit}=useForm<any>({values:{passing:get('school.passing_percentage','40'),warning:get('attendance.warning_percentage','75'),sms_time:get('attendance.sms_time','10:15'),test_weight:get('exam.class_test_weight','25'),exam_weight:get('exam.term_weight','75'),language:get('ui.language','en'),currency:get('school.currency','PKR')}});return <form onSubmit={handleSubmit((values)=>save.mutate({settings:{'school.passing_percentage':values.passing,'attendance.warning_percentage':values.warning,'attendance.sms_time':values.sms_time,'exam.class_test_weight':values.test_weight,'exam.term_weight':values.exam_weight,'ui.language':values.language,'school.currency':values.currency}}))} className="mx-auto max-w-3xl space-y-6"><div><h2 className="text-lg font-bold text-slate-800">Operational rules</h2><p className="mt-1 text-sm text-slate-500">These rules are editable and applied by attendance, result and communication workflows.</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="School passing percentage"><TextInput type="number" min="0" max="100" {...register('passing')}/></Field><Field label="Attendance warning percentage"><TextInput type="number" min="0" max="100" {...register('warning')}/></Field><Field label="Absent SMS dispatch time"><TextInput type="time" {...register('sms_time')}/></Field><Field label="Class test weight (%)"><TextInput type="number" min="0" max="100" {...register('test_weight')}/></Field><Field label="Term exam weight (%)"><TextInput type="number" min="0" max="100" {...register('exam_weight')}/></Field><Field label="Currency"><TextInput {...register('currency')}/></Field><Field label="Default interface language"><SelectInput {...register('language')}><option value="en">English</option><option value="ur">Urdu</option></SelectInput></Field></div><div className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600"><b className="text-slate-800">Related setup:</b> manage classes, sections, subjects and sessions from Academic Setup; timetable days and periods from Timetable; fee heads from Fees; gateway credentials from SMS & WhatsApp.</div><div className="border-t border-slate-100 pt-5"><ExamTypesPanel /></div><div className="flex justify-end"><Button type="submit" loading={save.isPending} icon={<SlidersHorizontal className="h-4 w-4"/>}>Save preferences</Button></div></form>}
