import { getDatabase } from '../../database';
import { ApiError } from '../utils/errors';
import { pagination, required } from '../utils/http';
import { bool, nullable, today } from '../utils/serializers';

type Recipient={student_id:number|null;name:string;phone:string;values:Record<string,string|number>};
export class CommunicationService {
  gateway(){return getDatabase().prepare('SELECT id,provider_name,api_url,api_key,sender_id,is_enabled,updated_at FROM sms_gateway_settings WHERE id=1').get()||{id:1,provider_name:'',api_url:'',api_key:'',sender_id:'',is_enabled:0};}
  saveGateway(input:Record<string,unknown>){const db=getDatabase();db.prepare(`INSERT INTO sms_gateway_settings (id,provider_name,api_url,api_key,sender_id,is_enabled,updated_at) VALUES (1,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET provider_name=excluded.provider_name,api_url=excluded.api_url,api_key=excluded.api_key,sender_id=excluded.sender_id,is_enabled=excluded.is_enabled,updated_at=CURRENT_TIMESTAMP`).run(nullable(input.provider_name),nullable(input.api_url),nullable(input.api_key),nullable(input.sender_id),bool(input.is_enabled)?1:0);return this.gateway();}
  templates(){return getDatabase().prepare('SELECT * FROM sms_templates ORDER BY name').all();}
  saveTemplate(input:Record<string,unknown>,id?:number){const db=getDatabase();const values=[required(input.code,'Template code'),required(input.name,'Template name'),required(input.body,'Message body'),input.status==='inactive'?'inactive':'active'];if(id){if(!db.prepare('UPDATE sms_templates SET code=?,name=?,body=?,status=? WHERE id=?').run(...values,id).changes)throw new ApiError(404,'Template not found');return db.prepare('SELECT * FROM sms_templates WHERE id=?').get(id);}const r=db.prepare('INSERT INTO sms_templates (code,name,body,status) VALUES (?,?,?,?)').run(...values);return db.prepare('SELECT * FROM sms_templates WHERE id=?').get(r.lastInsertRowid);}
  deleteTemplate(id:number){if(!getDatabase().prepare('DELETE FROM sms_templates WHERE id=?').run(id).changes)throw new ApiError(404,'Template not found');}
  logs(query:Record<string,unknown>){const {page,limit,offset}=pagination(query as never);const db=getDatabase();const where:string[]=['1=1'],p:unknown[]=[];if(query.status){where.push('l.status=?');p.push(query.status);}if(query.channel){where.push('l.channel=?');p.push(query.channel);}const total=(db.prepare(`SELECT COUNT(*) total FROM sms_logs l WHERE ${where.join(' AND ')}`).get(...p) as {total:number}).total;const data=db.prepare(`SELECT l.*,s.admission_no,s.first_name,s.last_name,u.full_name sent_by_name FROM sms_logs l LEFT JOIN students s ON s.id=l.student_id LEFT JOIN users u ON u.id=l.sent_by WHERE ${where.join(' AND ')} ORDER BY l.created_at DESC LIMIT ? OFFSET ?`).all(...p,limit,offset);return {data,pagination:{page,limit,total,totalPages:Math.max(1,Math.ceil(total/limit))}};}
  async send(input:Record<string,unknown>,userId:number){const channel=input.channel==='whatsapp'?'whatsapp':'sms';const recipients=this.resolveRecipients(input,channel);if(!recipients.length)throw new ApiError(422,'No valid recipients were found');const template=input.template_code?getDatabase().prepare('SELECT * FROM sms_templates WHERE code=? AND status=?').get(input.template_code,'active') as {code:string;body:string}|undefined:undefined;const raw=String(input.message||template?.body||'');if(!raw)throw new ApiError(422,'Message or template is required');const sent=[];for(const recipient of recipients){const text=this.render(raw,{student:recipient.name,phone:recipient.phone,...recipient.values,...(input.variables as Record<string,string|number>||{})});if(channel==='whatsapp')sent.push(this.whatsappLog(recipient,text,userId));else sent.push(await this.smsLog(recipient,text,template?.code,userId));}return {total:sent.length,logs:sent};}
  async resend(id:number,userId:number){const log=getDatabase().prepare('SELECT * FROM sms_logs WHERE id=?').get(id) as {student_id:number|null;phone:string;message:string;template_code:string|null;channel:string}|undefined;if(!log)throw new ApiError(404,'Message log not found');if(log.channel==='whatsapp')return this.whatsappLog({student_id:log.student_id,name:'',phone:log.phone,values:{}},log.message,userId);return this.smsLog({student_id:log.student_id,name:'',phone:log.phone,values:{}},log.message,log.template_code||undefined,userId);}
  whatsappUrl(phone:string,message:string){const clean=phone.replace(/\D/g,'').replace(/^0/,'92');if(!clean)return '';return `https://wa.me/${clean}?text=${encodeURIComponent(message)}`;}
  async sendAbsenceAlerts(date=today()) {const db=getDatabase();const rows=db.prepare(`SELECT s.id student_id,s.first_name || CASE WHEN s.last_name IS NOT NULL THEN ' '||s.last_name ELSE '' END name,COALESCE(s.whatsapp,s.phone) phone FROM attendance_records ar JOIN attendance_sessions a ON a.id=ar.attendance_session_id JOIN students s ON s.id=ar.student_id WHERE a.attendance_date=? AND ar.status='absent' AND COALESCE(s.phone,s.whatsapp) IS NOT NULL`).all(date) as {student_id:number;name:string;phone:string}[];if(!rows.length)return{total:0,logs:[]};return this.send({channel:'sms',template_code:'absent',recipients:rows.map(r=>({student_id:r.student_id,phone:r.phone,name:r.name})),variables:{date}},0);}
  async sendAttendanceWarnings() {
    const db = getDatabase();
    const threshold = Number((db.prepare("SELECT value FROM settings WHERE key='attendance.warning_percentage'").get() as { value: string } | undefined)?.value || 75);
    const session = db.prepare('SELECT id FROM school_sessions WHERE is_current=1').get() as { id: number } | undefined;
    if (!session) return { total: 0, logs: [] };
    const rows = db.prepare(`
      SELECT s.id student_id,s.first_name || CASE WHEN s.last_name IS NOT NULL THEN ' '||s.last_name ELSE '' END name,s.phone,
        COUNT(ar.id) total,COALESCE(SUM(ar.status IN ('present','late')),0) present
      FROM students s JOIN attendance_records ar ON ar.student_id=s.id JOIN attendance_sessions a ON a.id=ar.attendance_session_id
      WHERE a.session_id=? AND s.status='active' AND s.phone IS NOT NULL
      GROUP BY s.id HAVING total>0 AND (present*100.0/total) < ?
    `).all(session.id, threshold) as { student_id: number; name: string; phone: string; total: number; present: number }[];
    if (!rows.length) return { total: 0, logs: [] };
    return this.send({ channel: 'sms', template_code: 'attendance_warning', recipients: rows.map((row) => ({ student_id: row.student_id, name: row.name, phone: row.phone, percentage: Number((row.present * 100 / row.total).toFixed(1)) })) }, 0);
  }

  private resolveRecipients(input:Record<string,unknown>,channel:string){const db=getDatabase();if(Array.isArray(input.recipients)) return (input.recipients as unknown[]).map(raw => {
      const r = raw as Record<string, unknown>;
      const values = { ...(r.values && typeof r.values === 'object' ? r.values as Record<string, string | number> : {}), ...Object.fromEntries(Object.entries(r).filter(([key]) => !['student_id', 'name', 'phone', 'values'].includes(key)).map(([key, value]) => [key, String(value ?? '')])) } as Record<string, string | number>;
      return { student_id: r.student_id ? Number(r.student_id) : null, name: String(r.name || ''), phone: String(r.phone || ''), values };
    }).filter(r => r.phone);
    let students:Recipient[]=[];if(Array.isArray(input.student_ids)){const ids=(input.student_ids as unknown[]).map(Number).filter(Boolean);if(ids.length){const placeholders=ids.map(()=>'?').join(',');students=db.prepare(`SELECT id,first_name || CASE WHEN last_name IS NOT NULL THEN ' '||last_name ELSE '' END name,${channel==='whatsapp'?'COALESCE(whatsapp,phone)':'phone'} phone FROM students WHERE id IN (${placeholders})`).all(...ids).map((r:any)=>({student_id:r.id,name:r.name,phone:r.phone,values:{}}));}}
    else if(input.target==='unpaid'){students=db.prepare(`SELECT s.id,s.first_name || CASE WHEN s.last_name IS NOT NULL THEN ' '||s.last_name ELSE '' END name,${channel==='whatsapp'?'COALESCE(s.whatsapp,s.phone)':'s.phone'} phone,SUM(i.total-i.paid_amount) balance,MIN(i.due_date) due_date,MAX(fc.full_name) father_name,MAX(c.name) class_name,MAX(sec.name) section_name FROM invoices i JOIN students s ON s.id=i.student_id LEFT JOIN student_contacts fc ON fc.student_id=s.id AND fc.contact_type='father' LEFT JOIN enrollments e ON e.student_id=s.id AND e.status='active' LEFT JOIN classes c ON c.id=e.class_id LEFT JOIN sections sec ON sec.id=e.section_id WHERE i.status IN ('unpaid','partial','overdue') GROUP BY s.id HAVING balance>0`).all().map((r:any)=>({student_id:r.id,name:r.name,phone:r.phone,values:{student:r.name,student_name:r.name,father_name:r.father_name||'',class:r.class_name||'',section:r.section_name||'',due_amount:r.balance,amount:r.balance,due_date:r.due_date,school_name:(db.prepare("SELECT value FROM settings WHERE key='school.name'").get() as {value:string}|undefined)?.value||'School'}}));}
    else if(input.class_id){students=db.prepare(`SELECT s.id,s.first_name || CASE WHEN s.last_name IS NOT NULL THEN ' '||s.last_name ELSE '' END name,${channel==='whatsapp'?'COALESCE(s.whatsapp,s.phone)':'s.phone'} phone FROM enrollments e JOIN students s ON s.id=e.student_id WHERE e.class_id=? AND e.section_id IS ? AND e.status='active'`).all(Number(input.class_id),nullable(input.section_id)).map((r:any)=>({student_id:r.id,name:r.name,phone:r.phone,values:{}}));}
    return students.filter(r=>r.phone);
  }
  private async smsLog(recipient:Recipient,message:string,template:string|undefined,userId:number){const db=getDatabase();const r=db.prepare(`INSERT INTO sms_logs (student_id,phone,message,template_code,channel,status,sent_by) VALUES (?,?,?,?, 'sms','queued',?)`).run(recipient.student_id,recipient.phone,message,template||null,userId||null);const id=Number(r.lastInsertRowid);const gateway=this.gateway() as {is_enabled:number;api_url:string|null;api_key:string|null;sender_id:string|null};if(!gateway.is_enabled||!gateway.api_url)return db.prepare('SELECT * FROM sms_logs WHERE id=?').get(id);try{const response=await fetch(gateway.api_url,{method:'POST',headers:{'content-type':'application/json',...(gateway.api_key?{authorization:`Bearer ${gateway.api_key}`}:{})},body:JSON.stringify({to:recipient.phone,message,sender_id:gateway.sender_id})});const payload=await response.text();db.prepare(`UPDATE sms_logs SET status=?,provider_response=?,sent_at=CURRENT_TIMESTAMP WHERE id=?`).run(response.ok?'sent':'failed',payload.slice(0,2000),id);}catch(error){db.prepare(`UPDATE sms_logs SET status='failed',provider_response=? WHERE id=?`).run(error instanceof Error?error.message:'Gateway error',id);}return db.prepare('SELECT * FROM sms_logs WHERE id=?').get(id);}
  private whatsappLog(recipient:Recipient,message:string,userId:number){const r=getDatabase().prepare(`INSERT INTO sms_logs (student_id,phone,message,channel,status,sent_by,sent_at) VALUES (?,?,?,'whatsapp','sent',?,CURRENT_TIMESTAMP)`).run(recipient.student_id,recipient.phone,message,userId||null);return {...getDatabase().prepare('SELECT * FROM sms_logs WHERE id=?').get(r.lastInsertRowid) as object,url:this.whatsappUrl(recipient.phone,message)};}
  private render(text:string,values:Record<string,string|number>){return text.replace(/\{\{([a-z_]+)\}\}|\{([a-z_]+)\}/gi,(_,doubleKey,singleKey)=>{const key=doubleKey||singleKey;return String(values[key]??`{{${key}}}`);});}
}
