import { getDatabase } from '../../database';
import { today } from '../utils/serializers';

const scalar=(sql:string,...params:unknown[])=>Number((getDatabase().prepare(sql).get(...params) as {value:number|null}|undefined)?.value||0);
const dateOffset=(offset:number)=>{const date=new Date(`${today()}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+offset);return date.toISOString().slice(0,10);};
export class DashboardService {
  overview(){const db=getDatabase(),date=today(),month=date.slice(0,7);const totalStudents=scalar("SELECT COUNT(*) value FROM students WHERE status='active'");const boys=scalar("SELECT COUNT(*) value FROM students WHERE status='active' AND gender='male'");const girls=scalar("SELECT COUNT(*) value FROM students WHERE status='active' AND gender='female'");const teachers=scalar(`SELECT COUNT(*) value FROM staff s LEFT JOIN users u ON u.id=s.user_id WHERE s.status='active' AND (u.id IS NOT NULL AND EXISTS(SELECT 1 FROM roles r WHERE r.id=u.role_id AND r.code IN ('class_teacher','subject_teacher')) OR EXISTS(SELECT 1 FROM designations d WHERE d.id=s.designation_id AND lower(d.name) LIKE '%teacher%'))`);const staff=scalar("SELECT COUNT(*) value FROM staff WHERE status='active'");const attend=db.prepare(`SELECT COUNT(*) total,COALESCE(SUM(ar.status IN ('present','late')),0) present FROM attendance_records ar JOIN attendance_sessions a ON a.id=ar.attendance_session_id WHERE a.attendance_date=?`).get(date) as {total:number;present:number};const pending=scalar("SELECT COALESCE(SUM(total-paid_amount),0) value FROM invoices WHERE status IN ('unpaid','partial','overdue')");const todayCollection=scalar('SELECT COALESCE(SUM(amount),0) value FROM payments WHERE payment_date=?',date);const monthlyCollection=scalar("SELECT COALESCE(SUM(amount),0) value FROM payments WHERE substr(payment_date,1,7)=?",month);const otherIncome=scalar("SELECT COALESCE(SUM(amount),0) value FROM income_entries WHERE substr(income_date,1,7)=?",month);const expenses=scalar("SELECT COALESCE(SUM(amount),0) value FROM expenses WHERE substr(expense_date,1,7)=?",month);const totalRevenue=scalar('SELECT COALESCE(SUM(amount),0) value FROM payments')+scalar('SELECT COALESCE(SUM(amount),0) value FROM income_entries');
    return {cards:{total_students:totalStudents,boys,girls,teachers,staff,today_attendance:attend.total?Number((attend.present*100/attend.total).toFixed(1)):0,today_attendance_total:attend.total,fee_pending:pending,today_collection:todayCollection,monthly_collection:monthlyCollection,total_revenue:totalRevenue,monthly_income:monthlyCollection+otherIncome,monthly_expenses:expenses,net_income:monthlyCollection+otherIncome-expenses},charts:{weekly_attendance:this.weeklyAttendance(),financial:this.financial(),monthly_attendance:this.monthlyAttendance(),student_growth:this.studentGrowth()},recent_activity:this.activities(),upcoming_exams:this.upcomingExams(),birthdays:this.birthdays()};}
  private weeklyAttendance(){const db=getDatabase();return Array.from({length:7},(_,index)=>{const date=dateOffset(index-6);const row=db.prepare(`SELECT COUNT(*) total,COALESCE(SUM(ar.status IN ('present','late')),0) present FROM attendance_records ar JOIN attendance_sessions a ON a.id=ar.attendance_session_id WHERE a.attendance_date=?`).get(date) as {total:number;present:number};return {date,label:date.slice(5),percentage:row.total?Number((row.present*100/row.total).toFixed(1)):0,present:row.present,absent:row.total-row.present};});}
  private financial(){const months=Array.from({length:6},(_,index)=>{const d=new Date(`${today().slice(0,7)}-01T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()-(5-index));return d.toISOString().slice(0,7);});return months.map(month=>({month,collection:scalar("SELECT COALESCE(SUM(amount),0) value FROM payments WHERE substr(payment_date,1,7)=?",month),income:scalar("SELECT COALESCE(SUM(amount),0) value FROM income_entries WHERE substr(income_date,1,7)=?",month),expenses:scalar("SELECT COALESCE(SUM(amount),0) value FROM expenses WHERE substr(expense_date,1,7)=?",month)}));}
  private monthlyAttendance(){const db=getDatabase();const months=Array.from({length:6},(_,index)=>{const d=new Date(`${today().slice(0,7)}-01T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()-(5-index));return d.toISOString().slice(0,7);});return months.map(month=>{const row=db.prepare(`SELECT COUNT(*) total,COALESCE(SUM(ar.status IN ('present','late')),0) present FROM attendance_records ar JOIN attendance_sessions a ON a.id=ar.attendance_session_id WHERE substr(a.attendance_date,1,7)=?`).get(month) as {total:number;present:number};return {month,percentage:row.total?Number((row.present*100/row.total).toFixed(1)):0,present:row.present,total:row.total};});}
  private studentGrowth(){const months=Array.from({length:6},(_,index)=>{const d=new Date(`${today().slice(0,7)}-01T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()-(5-index));return d.toISOString().slice(0,7);});return months.map(month=>({month,admissions:scalar("SELECT COUNT(*) value FROM students WHERE substr(admission_date,1,7)=?",month),total:scalar("SELECT COUNT(*) value FROM students WHERE admission_date<=?",`${month}-31`)}));}
  private activities(){return getDatabase().prepare(`SELECT a.*,u.full_name user_name,u.photo_path FROM activity_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 8`).all();}
  private upcomingExams(){return getDatabase().prepare(`SELECT e.id,e.name,MIN(es.exam_date) exam_date,COUNT(es.id) subject_count FROM exams e JOIN exam_subjects es ON es.exam_id=e.id WHERE es.exam_date>=? AND e.status NOT IN ('archived','published') GROUP BY e.id ORDER BY exam_date LIMIT 6`).all(today());}
  private birthdays(){const db=getDatabase();return db.prepare(`SELECT id,admission_no,first_name,last_name,date_of_birth,photo_path FROM students WHERE status='active' AND strftime('%m-%d',date_of_birth)=strftime('%m-%d','now','localtime') ORDER BY first_name LIMIT 12`).all();}
}
