import { getDatabase } from '../../database';
import { ApiError } from '../utils/errors';
import { pagination, required } from '../utils/http';
import { nullable, number, today } from '../utils/serializers';

const currentSession = () => (getDatabase().prepare('SELECT id FROM school_sessions WHERE is_current=1').get() as { id: number } | undefined)?.id || (() => { throw new ApiError(422, 'Set a current academic session first'); })();

export class FeeService {
  heads() { return getDatabase().prepare('SELECT * FROM fee_heads ORDER BY name').all(); }
  saveHead(input: Record<string, unknown>, id?: number) {
    const db=getDatabase(); const values=[required(input.name,'Fee head name'),required(input.code,'Fee head code'),['one_time','recurring','optional','fine','transport','other'].includes(String(input.category))?input.category:'recurring',input.is_refundable?1:0,input.status==='inactive'?'inactive':'active'];
    if(id){if(!db.prepare('UPDATE fee_heads SET name=?,code=?,category=?,is_refundable=?,status=? WHERE id=?').run(...values,id).changes)throw new ApiError(404,'Fee head not found');return db.prepare('SELECT * FROM fee_heads WHERE id=?').get(id);}
    const r=db.prepare('INSERT INTO fee_heads (name,code,category,is_refundable,status) VALUES (?,?,?,?,?)').run(...values);return db.prepare('SELECT * FROM fee_heads WHERE id=?').get(r.lastInsertRowid);
  }
  deleteHead(id:number){const db=getDatabase();if((db.prepare('SELECT COUNT(*) count FROM fee_structures WHERE fee_head_id=?').get(id) as {count:number}).count)throw new ApiError(422,'This fee head is in use and cannot be deleted');if(!db.prepare('DELETE FROM fee_heads WHERE id=?').run(id).changes)throw new ApiError(404,'Fee head not found');}

  structures(query:Record<string,unknown>={}) { const db=getDatabase();const where:string[]=[];const p:unknown[]=[];if(query.class_id){where.push('fs.class_id=?');p.push(Number(query.class_id));}if(query.session_id){where.push('fs.session_id=?');p.push(Number(query.session_id));}return db.prepare(`SELECT fs.*,ss.name session_name,c.name class_name,sec.name section_name,fh.name fee_head_name,fh.code fee_head_code FROM fee_structures fs JOIN school_sessions ss ON ss.id=fs.session_id JOIN classes c ON c.id=fs.class_id LEFT JOIN sections sec ON sec.id=fs.section_id JOIN fee_heads fh ON fh.id=fs.fee_head_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY c.display_order,sec.name,fh.name`).all(...p); }
  saveStructure(input:Record<string,unknown>,id?:number){const db=getDatabase();const values=[Number(input.session_id)||currentSession(),Number(input.class_id),nullable(input.section_id),Number(input.fee_head_id),number(input.amount),['one_time','monthly','quarterly','annual'].includes(String(input.frequency))?input.frequency:'monthly',nullable(input.due_day),nullable(input.active_from),nullable(input.active_to),input.status==='inactive'?'inactive':'active'];if(!values[1]||!values[3])throw new ApiError(422,'Class and fee head are required');if(id){if(!db.prepare('UPDATE fee_structures SET session_id=?,class_id=?,section_id=?,fee_head_id=?,amount=?,frequency=?,due_day=?,active_from=?,active_to=?,status=? WHERE id=?').run(...values,id).changes)throw new ApiError(404,'Fee structure not found');return db.prepare('SELECT * FROM fee_structures WHERE id=?').get(id);}const r=db.prepare('INSERT INTO fee_structures (session_id,class_id,section_id,fee_head_id,amount,frequency,due_day,active_from,active_to,status) VALUES (?,?,?,?,?,?,?,?,?,?)').run(...values);return db.prepare('SELECT * FROM fee_structures WHERE id=?').get(r.lastInsertRowid);}
  deleteStructure(id:number){if(!getDatabase().prepare('DELETE FROM fee_structures WHERE id=?').run(id).changes)throw new ApiError(404,'Fee structure not found');}

  listInvoices(query:Record<string,unknown>) {
    const {page,limit,offset}=pagination(query as never);const conditions=['1=1'];const params:unknown[]=[];
    if(query.status){conditions.push('i.status=?');params.push(query.status);}if(query.student_id){conditions.push('i.student_id=?');params.push(Number(query.student_id));}if(query.class_id){conditions.push('e.class_id=?');params.push(Number(query.class_id));}if(query.billing_month){conditions.push('i.billing_month=?');params.push(query.billing_month);}if(typeof query.search==='string'&&query.search){const like=`%${query.search}%`;conditions.push('(s.admission_no LIKE ? OR s.first_name LIKE ? OR s.last_name LIKE ? OR i.invoice_no LIKE ?)');params.push(like,like,like,like);}
    const where=conditions.join(' AND '),db=getDatabase();const from=`FROM invoices i JOIN students s ON s.id=i.student_id LEFT JOIN enrollments e ON e.student_id=s.id AND e.status='active' LEFT JOIN classes c ON c.id=e.class_id LEFT JOIN sections sec ON sec.id=e.section_id`;
    const total=(db.prepare(`SELECT COUNT(*) total ${from} WHERE ${where}`).get(...params) as {total:number}).total;const data=db.prepare(`SELECT i.*,s.admission_no,s.first_name,s.last_name,e.roll_no,c.name class_name,sec.name section_name ${from} WHERE ${where} ORDER BY i.issue_date DESC,i.id DESC LIMIT ? OFFSET ?`).all(...params,limit,offset);
    return {data,pagination:{page,limit,total,totalPages:Math.max(1,Math.ceil(total/limit))}};
  }
  invoice(id:number){const db=getDatabase();const invoice=db.prepare(`SELECT i.*,s.admission_no,s.first_name,s.last_name,s.phone,s.whatsapp,e.roll_no,c.name class_name,sec.name section_name,ss.name session_name FROM invoices i JOIN students s ON s.id=i.student_id JOIN school_sessions ss ON ss.id=i.session_id LEFT JOIN enrollments e ON e.student_id=s.id AND e.status='active' LEFT JOIN classes c ON c.id=e.class_id LEFT JOIN sections sec ON sec.id=e.section_id WHERE i.id=?`).get(id);if(!invoice)throw new ApiError(404,'Invoice not found');return {...invoice as object,school:this.branding(),items:db.prepare(`SELECT ii.*,fh.name fee_head_name FROM invoice_items ii LEFT JOIN fee_heads fh ON fh.id=ii.fee_head_id WHERE ii.invoice_id=?`).all(id),payments:db.prepare(`SELECT p.*,pa.amount allocated_amount FROM payment_allocations pa JOIN payments p ON p.id=pa.payment_id WHERE pa.invoice_id=? ORDER BY p.payment_date DESC`).all(id)};}
  createInvoice(input:Record<string,unknown>,actorId:number){const studentId=Number(input.student_id);if(!studentId)throw new ApiError(422,'Student is required');if(!Array.isArray(input.items)||!input.items.length)throw new ApiError(422,'Add at least one fee item');return this.insertInvoice({student_id:studentId,session_id:Number(input.session_id)||currentSession(),issue_date:String(input.issue_date||today()),due_date:required(input.due_date,'Due date'),billing_month:nullable(input.billing_month),discount:number(input.discount),fine:number(input.fine),note:nullable(input.note),items:input.items as unknown[]},actorId);}
  generateInvoices(input:Record<string,unknown>,actorId:number){const db=getDatabase();const classId=Number(input.class_id),sessionId=Number(input.session_id)||currentSession(),sectionId=nullable(input.section_id),month=required(input.billing_month,'Billing month'),due=required(input.due_date,'Due date');if(!classId)throw new ApiError(422,'Class is required');const structures=db.prepare(`SELECT fs.*,fh.name fee_head_name FROM fee_structures fs JOIN fee_heads fh ON fh.id=fs.fee_head_id WHERE fs.session_id=? AND fs.class_id=? AND (fs.section_id IS NULL OR fs.section_id IS ?) AND fs.status='active' AND (fs.frequency='monthly' OR fs.frequency='quarterly' OR fs.frequency='annual')`).all(sessionId,classId,sectionId) as {fee_head_id:number;fee_head_name:string;amount:number}[];if(!structures.length)throw new ApiError(422,'No active fee structure was found for this class and section');const students=db.prepare(`SELECT student_id FROM enrollments WHERE session_id=? AND class_id=? AND section_id IS ? AND status='active'`).all(sessionId,classId,sectionId) as {student_id:number}[];let generated=0,skipped=0;db.transaction(()=>students.forEach(({student_id})=>{const exists=db.prepare(`SELECT id FROM invoices WHERE student_id=? AND session_id=? AND billing_month=? AND status<>'void'`).get(student_id,sessionId,month);if(exists){skipped++;return;}this.insertInvoice({student_id,session_id:sessionId,issue_date:String(input.issue_date||today()),due_date:due,billing_month:month,discount:0,fine:0,note:nullable(input.note),items:structures.map(s=>({fee_head_id:s.fee_head_id,description:s.fee_head_name,amount:s.amount,discount:0}))},actorId);generated++;}))();return {generated,skipped};}
  recordPayment(input:Record<string,unknown>,actorId:number){const db=getDatabase();const studentId=Number(input.student_id),amount=number(input.amount);if(!studentId||amount<=0)throw new ApiError(422,'Student and a positive payment amount are required');let paymentId=0;db.transaction(()=>{const allocations=this.allocations(studentId,amount,Array.isArray(input.allocations)?input.allocations:[]);const total=allocations.reduce((sum,a)=>sum+a.amount,0);if(Math.abs(total-amount)>0.009)throw new ApiError(422,'Payment allocations must equal the received amount');const receipt=this.nextReceipt();paymentId=Number(db.prepare(`INSERT INTO payments (receipt_no,student_id,payment_date,amount,method,reference_no,note,received_by) VALUES (?,?,?,?,?,?,?,?)`).run(receipt,studentId,String(input.payment_date||today()),amount,String(input.method||'cash'),nullable(input.reference_no),nullable(input.note),actorId).lastInsertRowid);const insert=db.prepare('INSERT INTO payment_allocations (payment_id,invoice_id,amount) VALUES (?,?,?)');const update=db.prepare('UPDATE invoices SET paid_amount=paid_amount+? WHERE id=?');allocations.forEach(a=>{insert.run(paymentId,a.invoice_id,a.amount);update.run(a.amount,a.invoice_id);this.refreshInvoice(a.invoice_id);});})();return this.receipt(paymentId);}
  receipt(paymentId:number){const db=getDatabase();const payment=db.prepare(`SELECT p.*,s.admission_no,s.first_name,s.last_name,u.full_name received_by_name FROM payments p JOIN students s ON s.id=p.student_id LEFT JOIN users u ON u.id=p.received_by WHERE p.id=?`).get(paymentId);if(!payment)throw new ApiError(404,'Receipt not found');return {...payment as object,school:this.branding(),allocations:db.prepare(`SELECT pa.amount,i.invoice_no,i.due_date FROM payment_allocations pa JOIN invoices i ON i.id=pa.invoice_id WHERE pa.payment_id=?`).all(paymentId)};}
  voidInvoice(id:number){const db=getDatabase();const invoice=this.invoice(id) as unknown as {paid_amount:number};if(invoice.paid_amount>0)throw new ApiError(422,'Paid invoices cannot be voided');db.prepare("UPDATE invoices SET status='void' WHERE id=?").run(id);}
  reports(query:Record<string,unknown>){const db=getDatabase();const from=String(query.from||`${new Date().getFullYear()}-01-01`),to=String(query.to||today());const collection=db.prepare(`SELECT payment_date date,SUM(amount) amount FROM payments WHERE payment_date BETWEEN ? AND ? GROUP BY payment_date ORDER BY payment_date`).all(from,to);const outstanding=db.prepare(`SELECT COALESCE(SUM(total-paid_amount),0) amount,COUNT(*) count FROM invoices WHERE status IN ('unpaid','partial','overdue')` ).get();const monthly=db.prepare(`SELECT substr(payment_date,1,7) month,SUM(amount) amount FROM payments WHERE payment_date BETWEEN ? AND ? GROUP BY substr(payment_date,1,7) ORDER BY month`).all(from,to);return {from,to,collection,monthly,outstanding};}
  private branding() {
    const rows = getDatabase().prepare("SELECT key,value FROM settings WHERE key IN ('school.name','school.logo','school.address','school.phone','school.email','school.website','school.tagline','school.principal_name')").all() as { key: string; value: string }[];
    return rows.reduce<Record<string, string>>((result, row) => { result[row.key.replace('school.', '')] = row.value; return result; }, {});
  }
  private insertInvoice(data:{student_id:number;session_id:number;issue_date:string;due_date:string;billing_month:unknown;discount:number;fine:number;note:unknown;items:unknown[]},actorId:number){const db=getDatabase();const items=data.items.map(raw=>{const item=raw as Record<string,unknown>;return {fee_head_id:nullable(item.fee_head_id),description:required(item.description,'Item description'),amount:number(item.amount),discount:number(item.discount)};});const subtotal=items.reduce((sum,item)=>sum+item.amount,0);const itemDiscount=items.reduce((sum,item)=>sum+item.discount,0);const discount=data.discount+itemDiscount;const total=Math.max(0,subtotal-discount+data.fine);const r=db.prepare(`INSERT INTO invoices (invoice_no,student_id,session_id,issue_date,due_date,billing_month,subtotal,discount,fine,total,note,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).run(this.nextInvoice(),data.student_id,data.session_id,data.issue_date,data.due_date,data.billing_month,subtotal,discount,data.fine,total,data.note,actorId);const id=Number(r.lastInsertRowid);const insert=db.prepare('INSERT INTO invoice_items (invoice_id,fee_head_id,description,amount,discount) VALUES (?,?,?,?,?)');items.forEach(item=>insert.run(id,item.fee_head_id,item.description,item.amount,item.discount));return this.invoice(id);}
  private allocations(studentId:number,amount:number,raw:unknown[]){const db=getDatabase();if(raw.length){return raw.map(item=>({invoice_id:Number((item as Record<string,unknown>).invoice_id),amount:number((item as Record<string,unknown>).amount)}));}let remaining=amount;const invoices=db.prepare(`SELECT id,total,paid_amount FROM invoices WHERE student_id=? AND status IN ('unpaid','partial','overdue') ORDER BY due_date,id`).all(studentId) as {id:number;total:number;paid_amount:number}[];const result:{invoice_id:number;amount:number}[]=[];for(const inv of invoices){const due=Math.max(0,inv.total-inv.paid_amount);const allocated=Math.min(due,remaining);if(allocated){result.push({invoice_id:inv.id,amount:allocated});remaining-=allocated;}if(!remaining)break;}if(remaining>0)throw new ApiError(422,'Payment is more than the student outstanding balance');return result;}
  private refreshInvoice(id:number){const db=getDatabase();const invoice=db.prepare('SELECT total,paid_amount,due_date FROM invoices WHERE id=?').get(id) as {total:number;paid_amount:number;due_date:string};const status=invoice.paid_amount>=invoice.total?'paid':invoice.paid_amount>0?'partial':invoice.due_date<today()?'overdue':'unpaid';db.prepare('UPDATE invoices SET status=? WHERE id=?').run(status,id);}
  private nextInvoice(){const d=today().replace(/-/g,'');const count=(getDatabase().prepare("SELECT COUNT(*) count FROM invoices WHERE invoice_no LIKE ?").get(`INV-${d}-%`) as {count:number}).count+1;return `INV-${d}-${String(count).padStart(4,'0')}`;}
  private nextReceipt(){const d=today().replace(/-/g,'');const count=(getDatabase().prepare("SELECT COUNT(*) count FROM payments WHERE receipt_no LIKE ?").get(`RCT-${d}-%`) as {count:number}).count+1;return `RCT-${d}-${String(count).padStart(4,'0')}`;}
}
