import { getDatabase } from '../../database';
import { ApiError } from '../utils/errors';
import { pagination, required } from '../utils/http';
import { nullable, number, today } from '../utils/serializers';

export class FinanceService {
  listIncome(query: Record<string, unknown>) { return this.list('income_entries', 'income_date', query); }
  listExpenses(query: Record<string, unknown>) { return this.list('expenses', 'expense_date', query, `LEFT JOIN expense_categories ec ON ec.id=expenses.category_id`, 'expenses.*,ec.name category_name'); }
  saveIncome(input: Record<string, unknown>, actor: number, id?: number) {
    const db=getDatabase();const values=[String(input.income_date||today()),required(input.category,'Income category'),number(input.amount),nullable(input.description),nullable(input.reference_no),actor];if(values[2] as number<=0)throw new ApiError(422,'Amount must be greater than zero');if(id){if(!db.prepare('UPDATE income_entries SET income_date=?,category=?,amount=?,description=?,reference_no=? WHERE id=?').run(...values.slice(0,5),id).changes)throw new ApiError(404,'Income entry not found');return db.prepare('SELECT * FROM income_entries WHERE id=?').get(id);}const r=db.prepare('INSERT INTO income_entries (income_date,category,amount,description,reference_no,created_by) VALUES (?,?,?,?,?,?)').run(...values);return db.prepare('SELECT * FROM income_entries WHERE id=?').get(r.lastInsertRowid);
  }
  saveExpense(input: Record<string, unknown>, actor:number,id?:number){const db=getDatabase();const values=[String(input.expense_date||today()),nullable(input.category_id),number(input.amount),nullable(input.description),nullable(input.payment_method),nullable(input.reference_no),actor];if(values[2] as number<=0)throw new ApiError(422,'Amount must be greater than zero');if(id){if(!db.prepare('UPDATE expenses SET expense_date=?,category_id=?,amount=?,description=?,payment_method=?,reference_no=? WHERE id=?').run(...values.slice(0,6),id).changes)throw new ApiError(404,'Expense entry not found');return db.prepare('SELECT * FROM expenses WHERE id=?').get(id);}const r=db.prepare('INSERT INTO expenses (expense_date,category_id,amount,description,payment_method,reference_no,created_by) VALUES (?,?,?,?,?,?,?)').run(...values);return db.prepare('SELECT * FROM expenses WHERE id=?').get(r.lastInsertRowid);}
  delete(type:'income_entries'|'expenses',id:number){if(!getDatabase().prepare(`DELETE FROM ${type} WHERE id=?`).run(id).changes)throw new ApiError(404,'Financial entry not found');}
  categories(){return getDatabase().prepare('SELECT * FROM expense_categories ORDER BY name').all();}
  saveCategory(name:string){const db=getDatabase();const r=db.prepare('INSERT INTO expense_categories (name) VALUES (?)').run(required(name,'Category name'));return db.prepare('SELECT * FROM expense_categories WHERE id=?').get(r.lastInsertRowid);}
  summary(query:Record<string,unknown>){const from=String(query.from||`${today().slice(0,7)}-01`),to=String(query.to||today()),db=getDatabase();const fee=(db.prepare('SELECT COALESCE(SUM(amount),0) total FROM payments WHERE payment_date BETWEEN ? AND ?').get(from,to) as {total:number}).total;const income=(db.prepare('SELECT COALESCE(SUM(amount),0) total FROM income_entries WHERE income_date BETWEEN ? AND ?').get(from,to) as {total:number}).total;const expenses=(db.prepare('SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE expense_date BETWEEN ? AND ?').get(from,to) as {total:number}).total;return {from,to,fee_collection:fee,other_income:income,expenses,net_income:fee+income-expenses};}
  private list(table:'income_entries'|'expenses', dateColumn:string,query:Record<string,unknown>,join='',select='*'){const {page,limit,offset}=pagination(query as never);const from=String(query.from||'0000-01-01'),to=String(query.to||'9999-12-31'),db=getDatabase();const qualifiedDate=`${table}.${dateColumn}`;const total=(db.prepare(`SELECT COUNT(*) total FROM ${table} ${join} WHERE ${qualifiedDate} BETWEEN ? AND ?`).get(from,to) as {total:number}).total;const data=db.prepare(`SELECT ${select} FROM ${table} ${join} WHERE ${qualifiedDate} BETWEEN ? AND ? ORDER BY ${qualifiedDate} DESC,${table}.id DESC LIMIT ? OFFSET ?`).all(from,to,limit,offset);return {data,pagination:{page,limit,total,totalPages:Math.max(1,Math.ceil(total/limit))}};}
}
