import { getDatabase } from '../../database';
import { ApiError } from '../utils/errors';
import { AttendanceService } from './attendance.service';
import { FeeService } from './fee.service';
import { FinanceService } from './finance.service';
import { AssessmentService } from './assessment.service';
import { CertificateService } from './certificate.service';

export class ReportService {
  studentList(query:Record<string,unknown>){const db=getDatabase();const where=['s.status<>\'archived\''];const p:unknown[]=[];if(query.class_id){where.push('e.class_id=?');p.push(Number(query.class_id));}if(query.section_id){where.push('e.section_id=?');p.push(Number(query.section_id));}if(query.status){where.push('s.status=?');p.push(query.status);}return {branding:this.branding(),rows:db.prepare(`SELECT s.admission_no,s.first_name,s.last_name,s.gender,s.phone,s.whatsapp,s.date_of_birth,e.roll_no,c.name class_name,sec.name section_name FROM students s LEFT JOIN enrollments e ON e.student_id=s.id AND e.status='active' LEFT JOIN classes c ON c.id=e.class_id LEFT JOIN sections sec ON sec.id=e.section_id WHERE ${where.join(' AND ')} ORDER BY c.display_order,sec.name,CAST(e.roll_no AS INTEGER),s.first_name`).all(...p)};}
  attendance(query:Record<string,unknown>){const service=new AttendanceService();if(query.month&&query.student_id)return {...this.branding(),type:'monthly',data:service.monthlySheet(query)};if(query.student_id)return {...this.branding(),type:'student_history',data:service.history(Number(query.student_id))};return {...this.branding(),type:'daily',date:query.date,data:service.dailyReport(query)};}
  fees(query:Record<string,unknown>){const db=getDatabase();return {...this.branding(),summary:new FeeService().reports(query),outstanding:db.prepare(`SELECT s.admission_no,s.first_name,s.last_name,s.phone,SUM(i.total-i.paid_amount) balance,MIN(i.due_date) oldest_due FROM invoices i JOIN students s ON s.id=i.student_id WHERE i.status IN ('unpaid','partial','overdue') GROUP BY s.id HAVING balance>0 ORDER BY balance DESC`).all()};}
  finance(query:Record<string,unknown>){const finance=new FinanceService();return {...this.branding(),summary:finance.summary(query),income:finance.listIncome(query).data,expenses:finance.listExpenses(query).data};}
  resultCard(examId:number,studentId:number,classId:number,sectionId:number|null){const result=new AssessmentService().results(examId,classId,sectionId).find((item:any)=>item.student.id===studentId);if(!result)throw new ApiError(404,'Result card was not found');return {...this.branding(),result};}
  awardList(examId:number,classId:number,sectionId:number|null){return {...this.branding(),results:new AssessmentService().results(examId,classId,sectionId)};}
  blankAwardList(examId:number,classId:number,sectionId:number|null){const db=getDatabase();const exam=db.prepare('SELECT name FROM exams WHERE id=?').get(examId);const subjects=db.prepare(`SELECT sub.name FROM exam_subjects es JOIN subjects sub ON sub.id=es.subject_id WHERE es.exam_id=? AND es.class_id=? AND es.section_id IS ? ORDER BY sub.name`).all(examId,classId,sectionId);const students=db.prepare(`SELECT s.admission_no,s.first_name,s.last_name,e.roll_no FROM enrollments e JOIN students s ON s.id=e.student_id WHERE e.class_id=? AND e.section_id IS ? AND e.status='active' ORDER BY CAST(e.roll_no AS INTEGER),s.first_name`).all(classId,sectionId);return {...this.branding(),exam,subjects,students};}
  timetable(query:Record<string,unknown>){const db=getDatabase();const classId=Number(query.class_id);if(!classId)throw new ApiError(422,'Class is required');const sessionId=Number(query.session_id)||(db.prepare('SELECT id FROM school_sessions WHERE is_current=1').get() as {id:number}).id;return {...this.branding(),rows:db.prepare(`SELECT te.weekday,p.name period_name,p.sequence,p.start_time,p.end_time,sub.name subject_name,st.first_name || CASE WHEN st.last_name IS NOT NULL THEN ' '||st.last_name ELSE '' END teacher_name,r.name room_name FROM timetable_entries te JOIN timetable_periods p ON p.id=te.period_id LEFT JOIN subjects sub ON sub.id=te.subject_id LEFT JOIN staff st ON st.id=te.teacher_id LEFT JOIN rooms r ON r.id=te.room_id WHERE te.session_id=? AND te.class_id=? AND te.section_id IS ? ORDER BY p.sequence,te.weekday`).all(sessionId,classId,query.section_id?Number(query.section_id):null)};}
  classTestCard(testId:number,studentId:number){const db=getDatabase();const row=db.prepare(`SELECT ct.id test_id,ct.name,ct.test_date,ct.total_marks,ct.passing_marks,ct.contribution_percent,ct.status,sub.name subject_name,c.name class_name,sec.name section_name,s.id student_id,s.admission_no,s.first_name,s.last_name,s.photo_path,e.roll_no,ctm.obtained_marks,ctm.remarks FROM class_tests ct JOIN subjects sub ON sub.id=ct.subject_id JOIN classes c ON c.id=ct.class_id LEFT JOIN sections sec ON sec.id=ct.section_id JOIN class_test_marks ctm ON ctm.class_test_id=ct.id JOIN students s ON s.id=ctm.student_id LEFT JOIN enrollments e ON e.student_id=s.id AND e.status='active' WHERE ct.id=? AND s.id=?`).get(testId,studentId) as Record<string,unknown>|undefined;if(!row)throw new ApiError(404,'Class test result was not found');const obtained=Number(row.obtained_marks||0);const total=Number(row.total_marks||0);const percentage=total?Number((obtained*100/total).toFixed(1)):0;return {...this.branding(),test:row,percentage,grade:percentage>=90?'A+':percentage>=80?'A':percentage>=70?'B':percentage>=60?'C':percentage>=50?'D':percentage>=40?'E':'F',status:obtained>=Number(row.passing_marks||0)?'Pass':'Fail'};}
  certificate(studentId:number,type:string){return new CertificateService().build(studentId,type);}
  private branding(){const db=getDatabase();const keys=['school.name','school.name_ur','school.logo','school.address','school.phone','school.email','school.website','school.tagline','school.principal_name'];const values=db.prepare(`SELECT key,value FROM settings WHERE key IN (${keys.map(()=>'?').join(',')})`).all(...keys) as {key:string;value:string}[];return values.reduce<Record<string,string>>((out,row)=>{out[row.key.replace('school.','')]=row.value;return out;},{});}
}
