import { getDatabase } from '../../database';
import { ApiError } from '../utils/errors';
import { required } from '../utils/http';

export class SettingsService {
  all() { const rows=getDatabase().prepare('SELECT key,value,group_name,updated_at FROM settings ORDER BY group_name,key').all() as {key:string;value:string;group_name:string;updated_at:string}[];return rows.reduce<Record<string,{value:string;group_name:string;updated_at:string}>>((map,row)=>{map[row.key]={value:row.value,group_name:row.group_name,updated_at:row.updated_at};return map;},{}); }
  update(input:Record<string,unknown>,userId:number){const settings=input.settings&&typeof input.settings==='object'?input.settings as Record<string,unknown>:input;const requestedTimeZone=settings['school.timezone'];if(requestedTimeZone!==undefined&&!['Asia/Karachi','UTC'].includes(String(requestedTimeZone)))throw new ApiError(422,'School time zone must be Asia/Karachi or UTC');const db=getDatabase();const upsert=db.prepare(`INSERT INTO settings (key,value,group_name,updated_by,updated_at) VALUES (?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,group_name=excluded.group_name,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP`);db.transaction(()=>Object.entries(settings).forEach(([key,value])=>{if(!/^[a-z][a-z0-9_.-]{1,80}$/i.test(key))throw new ApiError(422,`Invalid setting key: ${key}`);const known=db.prepare('SELECT group_name FROM settings WHERE key=?').get(key) as {group_name:string}|undefined;const supplied=input.groups&&typeof input.groups==='object'?(input.groups as Record<string,unknown>)[key]:undefined;upsert.run(key,String(value??''),String(supplied||known?.group_name||key.split('.')[0]||'general'),userId);}))();if(requestedTimeZone!==undefined)process.env.SCHOOL_TIMEZONE=String(requestedTimeZone);return this.all();}
  branding(){const keys=['school.name','school.name_ur','school.logo','school.address','school.phone','school.email','school.website','school.principal_name','school.tagline'];const rows=getDatabase().prepare(`SELECT key,value FROM settings WHERE key IN (${keys.map(()=>'?').join(',')})`).all(...keys) as {key:string;value:string}[];return rows.reduce<Record<string,string>>((out,row)=>{out[row.key.replace('school.','')]=row.value;return out;},{});}
  roles(){const db=getDatabase();return db.prepare(`SELECT r.*,COUNT(rp.permission_id) permission_count FROM roles r LEFT JOIN role_permissions rp ON rp.role_id=r.id GROUP BY r.id ORDER BY r.is_system DESC,r.name`).all();}
  role(id:number){const db=getDatabase();const role=db.prepare('SELECT * FROM roles WHERE id=?').get(id);if(!role)throw new ApiError(404,'Role not found');const permissions=db.prepare('SELECT p.code FROM permissions p JOIN role_permissions rp ON rp.permission_id=p.id WHERE rp.role_id=?').all(id) as {code:string}[];return {...role as object,permissions:permissions.map(p=>p.code)};}
  saveRole(input:Record<string,unknown>,id?:number){const db=getDatabase();const values=[required(input.code,'Role code'),required(input.name,'Role name'),input.name_ur||null,input.description||null];let roleId=id;if(id){const role=db.prepare('SELECT is_system FROM roles WHERE id=?').get(id) as {is_system:number}|undefined;if(!role)throw new ApiError(404,'Role not found');if(role.is_system&&String(input.code)!==(db.prepare('SELECT code FROM roles WHERE id=?').get(id) as {code:string}).code)throw new ApiError(422,'System role codes cannot be changed');db.prepare('UPDATE roles SET code=?,name=?,name_ur=?,description=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(...values,id);}else roleId=Number(db.prepare('INSERT INTO roles (code,name,name_ur,description,is_system) VALUES (?,?,?,?,0)').run(...values).lastInsertRowid);if(Array.isArray(input.permissions))this.setPermissions(roleId!,input.permissions);return this.role(roleId!);}
  deleteRole(id:number){const db=getDatabase();const role=db.prepare('SELECT is_system FROM roles WHERE id=?').get(id) as {is_system:number}|undefined;if(!role)throw new ApiError(404,'Role not found');if(role.is_system)throw new ApiError(422,'System roles cannot be deleted');if((db.prepare('SELECT COUNT(*) count FROM users WHERE role_id=?').get(id) as {count:number}).count)throw new ApiError(422,'Reassign users before deleting this role');db.prepare('DELETE FROM roles WHERE id=?').run(id);}
  private setPermissions(roleId:number,codes:unknown[]){const db=getDatabase();db.transaction(()=>{db.prepare('DELETE FROM role_permissions WHERE role_id=?').run(roleId);const insert=db.prepare('INSERT INTO role_permissions (role_id,permission_id) VALUES (?,?)');codes.forEach(code=>{const p=db.prepare('SELECT id FROM permissions WHERE code=?').get(String(code)) as {id:number}|undefined;if(p)insert.run(roleId,p.id);});})();}
}
