import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { Edit3, Plus, Trash2 } from 'lucide-react';
import { schoolApi } from '../../services/schoolApi';
import { queryKeys } from '../../services/queryKeys';
import { useMutationToast } from '../../hooks/useMutationToast';
import { Button } from '../common/Button';
import { DataTable } from '../common/DataTable';
import { Modal } from '../common/Modal';
import { ConfirmDialog } from '../common/ConfirmDialog';
import { Field, SelectInput, TextInput } from '../common/FormFields';
import { Badge } from '../common/Badge';
export function FeeHeadsPanel(){const [editor,setEditor]=useState<any>();const [remove,setRemove]=useState<any>();const {data=[],isLoading}=useQuery({queryKey:queryKeys.fees.heads,queryFn:schoolApi.fees.heads});const save=useMutationToast(({body,id}:any)=>schoolApi.fees.saveHead(body,id),{success:'Fee head saved',sync:['fees'],onSuccess:()=>setEditor(null)});const deleteHead=useMutationToast((id:number)=>schoolApi.fees.deleteHead(id),{success:'Fee head deleted',sync:['fees'],onSuccess:()=>setRemove(null)});return <><div className="mb-4 flex justify-end"><Button icon={<Plus className="h-4 w-4"/>} onClick={()=>setEditor({})}>Add fee head</Button></div><DataTable loading={isLoading} rows={data} columns={[{key:'code',header:'Code',render:(r:any)=><b>{r.code}</b>},{key:'name',header:'Fee head',render:(r:any)=>r.name},{key:'category',header:'Category',render:(r:any)=><span className="capitalize">{r.category.replace('_',' ')}</span>},{key:'refundable',header:'Refundable',render:(r:any)=>r.is_refundable?'Yes':'No'},{key:'status',header:'Status',render:(r:any)=><Badge value={r.status}/>},{key:'actions',header:'',className:'w-24 text-right',render:(r:any)=><><button onClick={()=>setEditor(r)} className="rounded-lg p-2 text-slate-400 hover:bg-brand-50 hover:text-brand-700"><Edit3 className="h-4 w-4"/></button><button onClick={()=>setRemove(r)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 className="h-4 w-4"/></button></>}]}/><Modal open={Boolean(editor)} onClose={()=>setEditor(null)} title={editor?.id?'Edit fee head':'Add fee head'} size="sm">{editor&&<HeadForm item={editor} onClose={()=>setEditor(null)} onSaved={(body)=>save.mutate({body,id:editor.id})}/>}</Modal><ConfirmDialog open={Boolean(remove)} onClose={()=>setRemove(null)} onConfirm={()=>remove&&deleteHead.mutate(remove.id)} loading={deleteHead.isPending} description="Delete this fee head? It can only be deleted when it is not used by a fee structure."/></>}
function HeadForm({item,onClose,onSaved}:{item:any;onClose:()=>void;onSaved:(data:any)=>void}){const {register,handleSubmit}=useForm({defaultValues:{category:'recurring',status:'active',...item}});return <form onSubmit={handleSubmit(onSaved)} className="space-y-4"><Field label="Name"><TextInput {...register('name',{required:true})}/></Field><Field label="Code"><TextInput {...register('code',{required:true})}/></Field><Field label="Category"><SelectInput {...register('category')}><option value="one_time">One-time</option><option value="recurring">Recurring</option><option value="optional">Optional</option><option value="fine">Fine</option><option value="transport">Transport</option><option value="other">Other</option></SelectInput></Field><Field label="Status"><SelectInput {...register('status')}><option value="active">Active</option><option value="inactive">Inactive</option></SelectInput></Field><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" {...register('is_refundable')}/> Refundable fee</label><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit">Save head</Button></div></form>}
