import { useState } from 'react';
import { useFieldArray, useForm } from 'react-hook-form';
import { useQuery } from '@tanstack/react-query';
import { CircleDollarSign, Eye, FilePlus2, Plus, Printer, ReceiptText, WandSparkles } from 'lucide-react';
import { schoolApi } from '../../services/schoolApi';
import { queryKeys } from '../../services/queryKeys';
import { useMutationToast } from '../../hooks/useMutationToast';
import { useGlobalSearch } from '../../context/GlobalSearchContext';
import { Button } from '../common/Button';
import { DataTable } from '../common/DataTable';
import { Modal } from '../common/Modal';
import { ConfirmDialog } from '../common/ConfirmDialog';
import { Field, SelectInput, TextArea, TextInput } from '../common/FormFields';
import { Badge } from '../common/Badge';
import { money, fullName, currentMonthInput, todayInput } from '../../utils/format';
import { escapeHtml, printHtml } from '../../utils/print';

export function InvoicesPanel() {
  const [page, setPage] = useState(1);
  const [status, setStatus] = useState('');
  const [search, setSearch] = useState('');
  const [detail, setDetail] = useState<any>();
  const [createOpen, setCreateOpen] = useState(false);
  const [generateOpen, setGenerateOpen] = useState(false);
  const [generationReport, setGenerationReport] = useState<{ generated: number; skipped: number } | null>(null);
  const [paymentFor, setPaymentFor] = useState<any>();
  const { query: globalQuery } = useGlobalSearch();
  const params = { page, limit: 20, status: status || undefined, search: globalQuery.trim() || search || undefined };
  const { data, isLoading } = useQuery({ queryKey: queryKeys.fees.invoices(params), queryFn: () => schoolApi.fees.invoices(params), placeholderData: (previous) => previous });
  const { data: heads = [] } = useQuery({ queryKey: queryKeys.fees.heads, queryFn: schoolApi.fees.heads });
  const { data: studentsPage } = useQuery({ queryKey: queryKeys.students.invoicePicker, queryFn: () => schoolApi.students.list({ limit: 100, status: 'active' }) });
  const { data: classes = [] } = useQuery({ queryKey: queryKeys.academic.classes(), queryFn: schoolApi.academic.classes });
  const { data: sections = [] } = useQuery({ queryKey: queryKeys.academic.sections(), queryFn: schoolApi.academic.sections });
  const { data: sessions = [] } = useQuery({ queryKey: queryKeys.academic.sessions, queryFn: schoolApi.academic.sessions });
  const canCreateInvoice = Boolean(studentsPage?.data?.length && heads.length);
  const create = useMutationToast((body: any) => schoolApi.fees.createInvoice(body), { success: 'Invoice created', sync: ['fees'], onSuccess: () => setCreateOpen(false) });
  const generate = useMutationToast((body: any) => schoolApi.fees.generate(body), { success: 'Monthly fee generation completed', sync: ['fees'], onSuccess: (result: any) => setGenerationReport(result) });
  const payment = useMutationToast((body: any) => schoolApi.fees.payment(body), { success: 'Payment collected', sync: ['fees'], onSuccess: (receipt: any) => { setPaymentFor(null); printReceipt(receipt); } });
  const openDetail = async (id: number) => setDetail(await schoolApi.fees.invoice(id));

  return <>
    <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center">
      <div className="flex min-w-0 flex-1 gap-2"><TextInput value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search student, registration no. or invoice" /><SelectInput className="w-36" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">All status</option>{['unpaid', 'partial', 'paid', 'overdue', 'void'].map((item) => <option key={item} value={item}>{item}</option>)}</SelectInput></div>
      <div className="flex gap-2"><Button variant="outline" disabled={!canCreateInvoice} icon={<WandSparkles className="h-4 w-4" />} onClick={() => setGenerateOpen(true)}>Generate Monthly Fees</Button><Button disabled={!canCreateInvoice} icon={<FilePlus2 className="h-4 w-4" />} onClick={() => setCreateOpen(true)}>Manual invoice</Button></div>
    </div>
    {!canCreateInvoice && <p className="mb-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Create active students and fee heads before issuing invoices. Use Student Management and Fee Heads to complete setup.</p>}
    <DataTable loading={isLoading} rows={data?.data} pagination={data?.pagination} onPage={setPage} columns={[
      { key: 'invoice', header: 'Invoice', render: (row: any) => <button className="text-left" onClick={() => void openDetail(row.id)}><b className="text-brand-700">{row.invoice_no}</b><small className="block text-slate-400">Due {row.due_date}</small></button> },
      { key: 'student', header: 'Student', render: (row: any) => <span><b>{fullName(row)}</b><small className="block text-slate-400">{row.admission_no} · {row.class_name || '—'}</small></span> },
      { key: 'total', header: 'Amount', render: (row: any) => <span><b>{money(row.total)}</b><small className="block text-slate-400">Paid {money(row.paid_amount)}</small></span> },
      { key: 'balance', header: 'Balance', render: (row: any) => <span className={Number(row.total) - Number(row.paid_amount) > 0 ? 'font-bold text-amber-700' : 'text-brand-700'}>{money(Number(row.total) - Number(row.paid_amount))}</span> },
      { key: 'status', header: 'Status', render: (row: any) => <Badge value={row.status} /> },
      { key: 'actions', header: '', className: 'w-20 text-right', render: (row: any) => <button onClick={() => void openDetail(row.id)} className="rounded-lg p-2 text-slate-400 hover:bg-brand-50 hover:text-brand-700"><Eye className="h-4 w-4" /></button> }
    ]} />
    <Modal open={Boolean(detail)} onClose={() => setDetail(null)} title="Fee invoice" size="lg">{detail && <InvoiceDetail invoice={detail} onCollect={() => { setPaymentFor(detail); setDetail(null); }} />}</Modal>
    <Modal open={createOpen} onClose={() => setCreateOpen(false)} title="Create manual invoice" size="lg"><ManualInvoiceForm students={studentsPage?.data || []} heads={heads} sessions={sessions} classes={classes} sections={sections} onClose={() => setCreateOpen(false)} onSave={(body: any) => create.mutate(body)} saving={create.isPending} /></Modal>
    <Modal open={generateOpen} onClose={() => { setGenerateOpen(false); setGenerationReport(null); }} title="Generate Monthly Fees" size="md"><GenerateForm classes={classes} sections={sections} sessions={sessions} result={generationReport} onClose={() => { setGenerateOpen(false); setGenerationReport(null); }} onSave={(body: any) => generate.mutate(body)} saving={generate.isPending} /></Modal>
    <Modal open={Boolean(paymentFor)} onClose={() => setPaymentFor(null)} title="Collect fee payment" size="md">{paymentFor && <PaymentForm invoice={paymentFor} onClose={() => setPaymentFor(null)} onSave={(body: any) => payment.mutate(body)} saving={payment.isPending} />}</Modal>
  </>;
}

function InvoiceDetail({ invoice, onCollect }: { invoice: any; onCollect: () => void }) {
  const balance = Number(invoice.total) - Number(invoice.paid_amount);
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xl font-extrabold text-slate-900">{invoice.invoice_no}</p><p className="text-sm text-slate-500">{fullName(invoice)} · {invoice.admission_no}</p></div><Badge value={invoice.status} /></div><div className="grid gap-3 sm:grid-cols-3"><Box label="Total" value={money(invoice.total)} /><Box label="Paid" value={money(invoice.paid_amount)} /><Box label="Balance" value={money(balance)} /></div><div className="overflow-hidden rounded-xl border border-slate-100"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">Description</th><th className="p-3 text-right">Amount</th></tr></thead><tbody>{invoice.items.map((item: any) => <tr key={item.id} className="border-t border-slate-50"><td className="p-3">{item.description}</td><td className="p-3 text-right font-semibold">{money(item.amount)}</td></tr>)}</tbody></table></div>{invoice.payments?.length ? <div><p className="mb-2 text-sm font-bold text-slate-700">Payments</p>{invoice.payments.map((payment: any) => <div key={payment.id} className="flex justify-between border-t border-slate-50 py-2 text-sm"><span>{payment.receipt_no} · {payment.payment_date}</span><b>{money(payment.allocated_amount)}</b></div>)}</div> : null}<div className="flex justify-end gap-2"><Button variant="outline" icon={<Printer className="h-4 w-4" />} onClick={() => printInvoice(invoice)}>Print invoice</Button><Button disabled={balance <= 0 || invoice.status === 'void'} icon={<CircleDollarSign className="h-4 w-4" />} onClick={onCollect}>Collect payment</Button></div></div>;
}

function ManualInvoiceForm({ students, heads, sessions, classes, sections, onClose, onSave, saving }: any) {
  const { register, control, handleSubmit, watch } = useForm<any>({ defaultValues: { issue_date: todayInput(), due_date: todayInput(), class_id: '', section_id: '', items: [{ fee_head_id: '', description: 'Monthly Fee', amount: '', discount: 0 }] } });
  const { fields, append, remove } = useFieldArray({ control, name: 'items' });
  const classId = watch('class_id');
  const sectionId = watch('section_id');
  const classSections = classId ? sections.filter((section: any) => String(section.class_id) === String(classId)) : [];
  const availableStudents = students.filter((student: any) => (!classId || String(student.class_id) === String(classId)) && (!sectionId || String(student.section_id) === String(sectionId)));
  return <form onSubmit={handleSubmit((values) => { const invoice = { ...values }; delete invoice.class_id; delete invoice.section_id; onSave(invoice); })} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Class filter"><SelectInput {...register('class_id')}><option value="">All classes</option>{classes.map((schoolClass: any) => <option key={schoolClass.id} value={schoolClass.id}>{schoolClass.name}</option>)}</SelectInput></Field><Field label="Section filter"><SelectInput disabled={!classId} {...register('section_id')}><option value="">{classId ? 'All sections' : 'Select class first'}</option>{classSections.map((section: any) => <option key={section.id} value={section.id}>{section.name}</option>)}</SelectInput></Field><Field label="Student"><SelectInput {...register('student_id', { required: true })}><option value="">Select a student</option>{availableStudents.map((student: any) => <option key={student.id} value={student.id}>{student.admission_no} · {fullName(student)}</option>)}</SelectInput></Field><Field label="Session"><SelectInput {...register('session_id')}><option value="">Current session</option>{sessions.map((session: any) => <option key={session.id} value={session.id}>{session.name}</option>)}</SelectInput></Field><Field label="Issue date"><TextInput type="date" {...register('issue_date')} /></Field><Field label="Due date"><TextInput type="date" {...register('due_date', { required: true })} /></Field><Field label="Billing month (optional)"><TextInput type="month" {...register('billing_month')} /></Field><Field label="Fine"><TextInput type="number" min="0" {...register('fine')} /></Field></div><div><div className="mb-2 flex justify-between"><p className="text-sm font-bold text-slate-700">Invoice items</p><Button type="button" variant="outline" className="h-8 text-xs" icon={<Plus className="h-3.5 w-3.5" />} onClick={() => append({ fee_head_id: '', description: '', amount: '', discount: 0 })}>Add item</Button></div>{fields.map((field, index) => <div key={field.id} className="mb-2 grid grid-cols-[1.2fr_1.5fr_100px_32px] gap-2"><SelectInput {...register(`items.${index}.fee_head_id`)}><option value="">Head</option>{heads.map((head: any) => <option key={head.id} value={head.id}>{head.name}</option>)}</SelectInput><TextInput placeholder="Description" {...register(`items.${index}.description`, { required: true })} /><TextInput type="number" min="0" placeholder="Amount" {...register(`items.${index}.amount`, { required: true })} /><button type="button" onClick={() => remove(index)} className="text-rose-500">×</button></div>)}</div><Field label="Note"><TextArea {...register('note')} /></Field><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" loading={saving}>Create invoice</Button></div></form>;
}

function GenerateForm({ classes, sections, sessions, result, onClose, onSave, saving }: any) {
  const [confirming, setConfirming] = useState(false);
  const [payload, setPayload] = useState<any>();
  const { register, handleSubmit, watch } = useForm<any>({ defaultValues: { issue_date: todayInput(), billing_month: currentMonthInput(), due_date: todayInput() } });
  const classId = watch('class_id');
  const sectionId = watch('section_id');
  const { data: eligible } = useQuery({ queryKey: queryKeys.fees.eligibleMonthlyFees(classId, sectionId), queryFn: () => schoolApi.students.list({ class_id: classId, section_id: sectionId || undefined, status: 'active', limit: 100 }), enabled: Boolean(classId) });
  const { data: structures = [] } = useQuery({ queryKey: queryKeys.fees.generationStructures(classId), queryFn: () => schoolApi.fees.structures({ class_id: classId }), enabled: Boolean(classId) });
  const submit = (values: any) => { setPayload(values); setConfirming(true); };
  return <><form onSubmit={handleSubmit(submit)} className="space-y-4"><p className="rounded-xl bg-brand-50 p-3 text-sm text-brand-800">Creates one monthly invoice for every eligible active student. Existing non-void invoices for the selected billing month are automatically skipped.</p><div className="grid gap-4 sm:grid-cols-2"><Field label="Session"><SelectInput {...register('session_id')}><option value="">Current session</option>{sessions.map((session: any) => <option key={session.id} value={session.id}>{session.name}</option>)}</SelectInput></Field><Field label="Class"><SelectInput {...register('class_id', { required: true })}><option value="">Select class</option>{classes.map((schoolClass: any) => <option key={schoolClass.id} value={schoolClass.id}>{schoolClass.name}</option>)}</SelectInput></Field><Field label="Section"><SelectInput disabled={!classId} {...register('section_id')}><option value="">{classId ? 'No / all section' : 'Select class first'}</option>{sections.filter((section: any) => String(section.class_id) === String(classId)).map((section: any) => <option key={section.id} value={section.id}>{section.name}</option>)}</SelectInput></Field><Field label="Billing month"><TextInput type="month" {...register('billing_month', { required: true })} /></Field><Field label="Issue date"><TextInput type="date" {...register('issue_date')} /></Field><Field label="Due date"><TextInput type="date" {...register('due_date', { required: true })} /></Field></div>{classId && <div className="grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-sm"><span><b>{eligible?.pagination.total || 0}</b> eligible active students</span><span><b>{structures.length}</b> fee structures found</span></div>}{result && <div className="rounded-xl border border-brand-100 bg-brand-50 p-3 text-sm text-brand-900"><b>Generation complete:</b> {result.generated} invoice(s) created, {result.skipped} duplicate invoice(s) skipped.</div>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Close</Button><Button type="submit" loading={saving} disabled={!classId || !structures.length}>Review generation</Button></div></form><ConfirmDialog open={confirming} onClose={() => setConfirming(false)} onConfirm={() => { if (payload) onSave(payload); setConfirming(false); }} loading={saving} title="Generate Monthly Fees" confirmLabel="Generate invoices" description={`Generate monthly invoices for ${eligible?.pagination.total || 0} eligible student(s)? Duplicate invoices for this month will be skipped.`} /></>;
}

function PaymentForm({ invoice, onClose, onSave, saving }: any) {
  const balance = Math.max(0, Number(invoice.total) - Number(invoice.paid_amount));
  const { register, handleSubmit } = useForm<any>({ defaultValues: { student_id: invoice.student_id, amount: balance, payment_date: todayInput(), method: 'cash', allocations: [{ invoice_id: invoice.id, amount: balance }] } });
  return <form onSubmit={handleSubmit((values) => { values.allocations[0].amount = values.amount; onSave(values); })} className="space-y-4"><div className="rounded-xl bg-brand-50 p-3"><p className="font-bold text-brand-900">{invoice.invoice_no} · {fullName(invoice)}</p><p className="mt-1 text-sm text-brand-700">Outstanding balance: {money(balance)}</p></div><input type="hidden" {...register('student_id')} /><input type="hidden" {...register('allocations.0.invoice_id')} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Amount received"><TextInput type="number" min="1" max={balance} step="0.01" {...register('amount', { required: true })} /></Field><Field label="Payment date"><TextInput type="date" {...register('payment_date')} /></Field><Field label="Method"><SelectInput {...register('method')}><option value="cash">Cash</option><option value="bank">Bank transfer</option><option value="online">Online</option><option value="cheque">Cheque</option></SelectInput></Field><Field label="Reference no."><TextInput {...register('reference_no')} /></Field></div><Field label="Note"><TextArea {...register('note')} /></Field><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" loading={saving} icon={<ReceiptText className="h-4 w-4" />}>Collect & print receipt</Button></div></form>;
}

const Box = ({ label, value }: { label: string; value: string }) => <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-lg font-extrabold text-slate-800">{value}</p></div>;
function printInvoice(invoice: any) { printHtml(`<div class="header"><div style="display:flex;align-items:center;gap:10px">${invoice.school?.logo ? `<img src="${escapeHtml(invoice.school.logo)}" style="width:42px;height:42px;object-fit:contain"/>` : ''}<div><h1>${escapeHtml(invoice.school?.name || 'School')} · Fee Invoice</h1><p class="muted">${escapeHtml(invoice.invoice_no)}</p></div></div><div class="right"><strong>${escapeHtml(fullName(invoice))}</strong><br/>${escapeHtml(invoice.admission_no)}</div></div><p>Issue date: ${escapeHtml(invoice.issue_date)} &nbsp; Due date: ${escapeHtml(invoice.due_date)}</p><table><thead><tr><th>Description</th><th class="right">Amount</th></tr></thead><tbody>${invoice.items.map((item: any) => `<tr><td>${escapeHtml(item.description)}</td><td class="right">${money(item.amount)}</td></tr>`).join('')}<tr><td><strong>Total</strong></td><td class="right"><strong>${money(invoice.total)}</strong></td></tr></tbody></table><div style="margin-top:70px;display:flex;justify-content:space-between"><span>Parent signature</span><span>${escapeHtml(invoice.school?.principal_name || 'Authorized signature')}</span></div>`, invoice.invoice_no); }
function printReceipt(receipt: any) { printHtml(`<div class="header"><div style="display:flex;align-items:center;gap:10px">${receipt.school?.logo ? `<img src="${escapeHtml(receipt.school.logo)}" style="width:42px;height:42px;object-fit:contain"/>` : ''}<div><h1>${escapeHtml(receipt.school?.name || 'School')} · Fee Payment Receipt</h1><p class="muted">${escapeHtml(receipt.receipt_no)}</p></div></div><div class="right">${escapeHtml(receipt.payment_date)}</div></div><p>Received from <strong>${escapeHtml(fullName(receipt))}</strong> (${escapeHtml(receipt.admission_no)})</p><table><thead><tr><th>Invoice</th><th>Due date</th><th class="right">Allocated</th></tr></thead><tbody>${receipt.allocations.map((item: any) => `<tr><td>${escapeHtml(item.invoice_no)}</td><td>${escapeHtml(item.due_date)}</td><td class="right">${money(item.amount)}</td></tr>`).join('')}<tr><td colspan="2"><strong>Total received</strong></td><td class="right"><strong>${money(receipt.amount)}</strong></td></tr></tbody></table><p style="margin-top:28px">Payment method: ${escapeHtml(receipt.method)}</p><div style="margin-top:70px;display:flex;justify-content:space-between"><span>Parent signature</span><span>${escapeHtml(receipt.school?.principal_name || 'Authorized signature')}</span></div>`, receipt.receipt_no); }
