import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { Edit3, Plus, ShieldCheck, Trash2 } from 'lucide-react';
import { schoolApi } from '../../services/schoolApi';
import { queryKeys } from '../../services/queryKeys';
import { useMutationToast } from '../../hooks/useMutationToast';
import { Button } from '../common/Button';
import { DataTable } from '../common/DataTable';
import { Modal } from '../common/Modal';
import { ConfirmDialog } from '../common/ConfirmDialog';
import { Field, TextArea, TextInput } from '../common/FormFields';
export function RolesPanel(){const [editor,setEditor]=useState<any>();const [remove,setRemove]=useState<any>();const {data:roles=[],isLoading}=useQuery({queryKey:queryKeys.settings.roles,queryFn:schoolApi.settings.roles});const {data:permissions=[]}=useQuery({queryKey:queryKeys.settings.permissions,queryFn:schoolApi.users.permissions});const save=useMutationToast(({body,id}:any)=>schoolApi.settings.saveRole(body,id),{success:'Role saved',sync:['users'],onSuccess:()=>setEditor(null)});const deleteRole=useMutationToast((id:number)=>schoolApi.settings.deleteRole(id),{success:'Role deleted',sync:['users'],onSuccess:()=>setRemove(null)});const edit=async(role:any)=>setEditor(await schoolApi.settings.role(role.id));return <><div className="mb-4 flex justify-end"><Button icon={<Plus className="h-4 w-4"/>} onClick={()=>setEditor({permissions:[]})}>Create role</Button></div><DataTable loading={isLoading} rows={roles} columns={[{key:'role',header:'Role',render:(r:any)=><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-brand-600"/><span><b>{r.name}</b><small className="block text-slate-400">{r.code}</small></span></span>},{key:'description',header:'Description',render:(r:any)=>r.description||'—'},{key:'permissions',header:'Permissions',render:(r:any)=>r.permission_count},{key:'system',header:'Type',render:(r:any)=>r.is_system?'System role':'Custom role'},{key:'actions',header:'',className:'w-24 text-right',render:(r:any)=><><button onClick={()=>void edit(r)} className="rounded-lg p-2 text-slate-400 hover:bg-brand-50 hover:text-brand-700"><Edit3 className="h-4 w-4"/></button>{!r.is_system&&<button onClick={()=>setRemove(r)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 className="h-4 w-4"/></button>}</>}]}/><Modal open={Boolean(editor)} onClose={()=>setEditor(null)} title={editor?.id?'Edit role permissions':'Create role'} size="lg">{editor&&<RoleForm item={editor} permissions={permissions} onClose={()=>setEditor(null)} onSave={(body)=>save.mutate({id:editor.id,body})}/>}</Modal><ConfirmDialog open={Boolean(remove)} onClose={()=>setRemove(null)} onConfirm={()=>remove&&deleteRole.mutate(remove.id)} loading={deleteRole.isPending} description="Delete this custom role? Assign any users to another role first."/></>}
function RoleForm({item,permissions,onClose,onSave}:{item:any;permissions:any[];onClose:()=>void;onSave:(v:any)=>void}){const {register,handleSubmit,watch}=useForm<any>({defaultValues:{permissions:[],...item}});const selected=watch('permissions')||[];const modules=Array.from(new Set(permissions.map((p:any)=>p.module)));return <form onSubmit={handleSubmit(onSave)} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Role name"><TextInput {...register('name',{required:true})}/></Field><Field label="Role code"><TextInput disabled={item.is_system} {...register('code',{required:true})}/></Field><Field label="Urdu name"><TextInput {...register('name_ur')}/></Field><Field label="Description"><TextArea className="min-h-[42px]" {...register('description')}/></Field></div><div><div className="mb-2 flex items-center justify-between"><p className="text-sm font-bold text-slate-700">Role permissions</p><span className="text-xs text-slate-500">{selected.length} selected</span></div><div className="max-h-[52vh] space-y-3 overflow-auto rounded-2xl border border-slate-100 p-4">{modules.map((module)=>{const group=permissions.filter((p:any)=>p.module===module);return <div key={module}><p className="mb-2 text-xs font-bold uppercase tracking-wide text-brand-700">{module}</p><div className="grid gap-2 sm:grid-cols-2">{group.map((permission:any)=><label key={permission.id} className="flex items-center gap-2 rounded-lg px-2 py-1.5 text-sm text-slate-600 hover:bg-slate-50"><input type="checkbox" value={permission.code} checked={selected.includes(permission.code)} {...register('permissions')}/>{permission.label}</label>)}</div></div>})}</div></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit">Save role</Button></div></form>}
